# Generated by Django 5.1 on 2024-10-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0001_initial'),
        ('places', '0002_alter_comment_options_remove_place_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='places.place'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='places',
            field=models.ManyToManyField(related_name='collections', through='placeCollection.CollectionItem', to='places.place'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
