# Generated by Django 5.1 on 2024-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
